# Generated by Django 4.1.7 on 2023-05-08 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
